### ISSUE TITLE
Fix Rezel ?

### ISSUE THREAD

**Issue by Lieunoir** [Nysciciel/BABA-IS-US#2]
3d2376ff9c22b9b63433b284a5910cebf8215507
Seems like you an issue with Rezel, care to elaborate ?

**Comment by regar42** [comment]
I think they just have an issue with the concept of coding.
They have to channel these bad feelings at something eh?

**Comment by Lieunoir** [comment]
I think I am going to directly contact the maintainers, they don't seem to check their issues.

**Comment by regar42** [comment]
I'm not surprised, regarding who are the members of the script-kiddie team behind this project.

**Comment by Maxwell1447** [comment]
Maybe it's not an issue and you thought it was but actually, it wasn't...
Regards

**Comment by Lieunoir** [comment]
I don't really see what Wamzaa has to do with this.

**Comment by Maxwell1447** [comment]
Glad you raise this point. Wamzaa is not the kind of person I can trust for this.
